In [1]:
import numpy as np


1. array()

    The array() function is used to create a NumPy array from a list.

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
#How to convert list into Array

my_list = [[10, 20, 30, 40,50],[60,70,80,90,100]]
arr = np.array(my_list)

print(arr)
print(type(arr))


[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
<class 'numpy.ndarray'>


2. zeros()

     The zeros() function creates an array filled with zeros. 

In [8]:
#Syantex-
    # np.zeros(size)
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


3. ones()

    The ones() function creates an array filled with ones.

In [11]:
import numpy as np

arr = np.ones(5)

print(arr)

[1. 1. 1. 1. 1.]


In [12]:
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


4. arange()

     The arange() function creates a sequence of numbers.

In [9]:
# Syntex--  np.arrange(start, stop, step)
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [11]:
arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


5. linspace()

      The linspace() function creates evenly spaced numbers between a start and stop value.

      Syntex-- np.linspace(start, stop, number_of_values)

In [13]:
arr = np.linspace(1, 10, 5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


Interview Question

Q: What is the difference between arange() and linspace()?

Answer:

arange() creates values using a fixed step size.
linspace() creates a fixed number of evenly spaced values.

1. eye()

    The eye() function creates an identity matrix.

    An identity matrix is a square matrix in which:

    All diagonal elements are 1
    All other elements are 0

    Syntax--
          np.eye(rows)

In [15]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7.random.rand()

     The random.rand() function generates random decimal (floating-point) numbers between 0 and 1.

Syntax --- np.random.rand(size)

In [17]:
arr = np.random.rand(5)
print(arr)

[0.36130854 0.29598375 0.06953508 0.45008518 0.29427585]


In [18]:
#2 D
arr = np.random.rand(2,3)
print(arr)

[[0.83323991 0.01816337 0.91699646]
 [0.12671387 0.42368017 0.13366827]]


Use--
   Generating sample data
   Machine Learning
   Simulations
   Testing programs

In [ ]:
8.random.randint()

   The random.randint() function generates random integers within a specified range.

Syntax---- np.random.randint(low, high, size)
            low → Starting number (included)
            high → Ending number (not included)
            size → Number of random values

In [20]:
arr = np.random.randint(1, 10, 5)
print(arr)

[5 4 7 2 1]


In [22]:
#2D
arr = np.random.randint(1, 20, (2,3))
print(arr)

[[8 7 8]
 [9 8 9]]


In [ ]:
⭐ Interview Question 1

Q. What does np.eye() do?

✨ Answer
✅ Creates an Identity Matrix.
✅ Diagonal elements = 1
✅ All other elements = 0
✅ Used in Linear Algebra, Machine Learning, and Matrix Operations.

One-line Answer:

np.eye() creates an identity matrix, where all diagonal elements are 1 and all other elements are 0.

⭐ Interview Question 2

Q. What is the difference between np.random.rand() and np.random.randint()?

✨ Answer
 np.random.rand()	                                    np.random.randint()
✅ Generates random floating-point (decimal) numbers	✅ Generates random integer numbers
✅ Range: 0 to 1	                                    ✅ Range: User-defined
✅ Example: 0.45, 0.89	                                ✅ Example: 5, 12, 18

In [ ]:
+++++++++++++++++++++++++++++ PRACTICE+++++++++++++++++++++++++++++++

In [ ]:
🟢 Basic Level (1–15)


In [26]:
# 1.Create a NumPy array containing the numbers 1 to 5.
arr = np.arange(1,6)
print(arr)


[1 2 3 4 5]


In [31]:
# 2.Create an array of 10 even numbers.
arr = np.arange(2,21,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [33]:
# 3.Create a 1D array containing your favorite numbers.
fav_numbers = np.array([1, 7, 19, 21, 99])
print(fav_numbers)


[ 1  7 19 21 99]


In [35]:
# 4.Create a 2D array with two rows and three columns.

#m1-
arr = np.zeros((2, 3))
print(arr)

#m2
arr = np.arange(1, 7).reshape(2, 3)
print(arr)

#m3
arr = np.ones((2, 3))
print(arr)

#m4
arr = np.full((2, 3), 5)
print(arr)


In [37]:
# 5.Create a 3×3 array filled with zeros.
arr =np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
#6.Create a 5×5 array filled with ones
arr = np.ones((5,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:
# 7.Create a 4×4 identity matrix.
arr = np.eye(4,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [43]:
# 8.Create an array containing numbers from 1 to 20.
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [48]:
# 9.Create an array containing numbers from 10 to 50 with a step of 5.
arr = np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]


In [51]:
# 10.Create an array of numbers from 50 to 1 in reverse order.
arr = np.arange(50,0,-1)
print(arr)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1]


In [52]:
# 11.Create an array of 5 evenly spaced numbers between 0 and 1.
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [53]:
# 12.Create an array of 11 evenly spaced numbers between 10 and 20.
arr = np.linspace(10,20,11)
print(arr)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


In [55]:
# 13.Generate 10 random decimal numbers.
arr = np.random.rand(10)
print(arr)

[0.27723511 0.19828396 0.02183716 0.36942756 0.37124574 0.51940401
 0.14323436 0.88030312 0.67566049 0.39255685]


In [58]:
# 14.Generate 10 random integers between 1 and 100.
arr = np.random.randint(1,100,10)
print(arr)

[94 35 42 52 33 53 93 85 91 66]


In [61]:
# 15.Create a 2×3 array of random decimal numbers.
arr = np.random.rand(2,3)
print(arr)

[[0.44082301 0.91027193 0.69420555]
 [0.04600388 0.66175925 0.98547004]]


In [ ]:
🟡 Intermediate Level (16–35)

In [63]:
# 16.Create a 3×4 array of zeros.
arr =np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [65]:
# 17.Create a 4×2 array of ones.
arr = np.ones((4,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [66]:
# 18.Create a 5×5 identity matrix.
arr = np.eye(5,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [67]:
# 19.Create a sequence of odd numbers from 1 to 99.
arr = np.arange(1, 100, 2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [71]:
# 20.Create a sequence of multiples of 7 from 7 to 70.
arr = np.arange(7,71,7)
print(arr)

[ 7 14 21 28 35 42 49 56 63 70]


In [73]:
# 21.Create an array from 100 to 200 with a step of 10.
arr = np.arange(100,201,10)
print(arr)

[100 110 120 130 140 150 160 170 180 190 200]


In [75]:
# 22.Generate a 4×4 array of random integers between 10 and 50.
arr = np.random.randint(10,50,(4,4))
print(arr)

[[35 13 23 31]
 [37 48 12 44]
 [42 24 18 23]
 [43 13 26 20]]


In [76]:
# 23.Generate a 5×5 array of random decimal numbers.
arr = np.random.rand(5,5)
print(arr)

[[0.01657491 0.28686148 0.9182176  0.27802786 0.19391001]
 [0.50099481 0.94723879 0.10627101 0.71599228 0.93026007]
 [0.71870403 0.31156213 0.17539795 0.95040338 0.68631823]
 [0.79170435 0.63828744 0.53675727 0.91100004 0.57528845]
 [0.10391407 0.52444028 0.15939416 0.54308548 0.43057437]]


In [77]:
# 24.Create an array using linspace() between 5 and 15 with 6 values.
arr = np.linspace(5,15,6)
print(arr)

[ 5.  7.  9. 11. 13. 15.]


In [79]:
# 25.Create a 10×10 matrix filled with zeros.
arr = np.zeros((10,10))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [80]:
# 26.Create a 10×10 matrix filled with ones.
arr = np.ones((10,10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [81]:
# 27.Create a 6×6 identity matrix.
arr = np.eye(6,6)
print(arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [83]:
# 28.Generate 20 random integers between 50 and 100.
arr = np.random.randint(50,100,20)
print(arr)

[56 58 87 54 77 68 83 69 90 55 91 92 51 94 75 75 55 89 61 85]


In [84]:
# 29.Generate 15 random decimal numbers.
arr = np.random.rand(15)
print(arr)

[0.24233321 0.82656219 0.77177078 0.80936102 0.80475656 0.26472405
 0.25947857 0.46631097 0.85700308 0.27222235 0.18231993 0.91675482
 0.04936872 0.90964944 0.53427183]


In [86]:
# 30.Create a 3×5 array using rand().
arr = np.random.rand(3,5)
print(arr)

[[0.18757763 0.80558978 0.11708144 0.46832994 0.73373511]
 [0.2000948  0.49001114 0.82590103 0.64286738 0.78905509]
 [0.43053768 0.25829377 0.83931967 0.12159896 0.06317325]]


In [92]:
# 31.Create a 4×4 matrix using randint().
arr = np.random.randint(1,100,(4,4))
print(arr)

[[23 95 20 79]
 [21 62 40 72]
 [89 54  8 17]
 [61 56  4 57]]


In [93]:
# 32.Create an array of multiples of 3 from 3 to 60.
arr = np.arange(3,61,3)
print(arr)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60]


In [94]:
# 33.Create an array of multiples of 5 from 5 to 100.
arr = np.arange(5,101,5)
print(arr)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [95]:
# 34.Create an array of numbers from -10 to 10.
arr = np.arange(-10,10)
print(arr)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]


In [97]:
# 35.Create 9 equally spaced values between -1 and 1.
arr = np.linspace(-1,1,9)
print(arr)

[-1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75  1.  ]


In [ ]:
🔴 Advanced Level (36–50)

In [99]:
# 36.Create a checkerboard-like 8×8 matrix using only array creation functions.
arr = np.zeros((8,8))

# syntex--- array[row_start:row_end:step, column_start:column_end:step]
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [100]:
# 37.Create a 5×5 identity matrix and multiply every element by 10.
arr = np.eye(5,5)
print(10*arr)

[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]


In [102]:
# 38.Generate a 100-element random integer array between 1 and 100.
arr = np.random.randint(1,101,100)
print(arr)

[ 60   6  90  98  49  18  65  72  45   8   9  23  14  73  23  17  28  34
  74  53  66  66  79  46  93  84   4  33  28  39  41  20 100  99  82  97
  47  17  25  51  39  12  51  46  66  85  41  38  42  36  20  17  89  11
   8  76  98  66   9 100  79  22  16   5  23  31  34  62  94   5  42  91
  40  83  74  89  19  90  62  53  34  84   8  49  14  67   6  89  97  53
  23  42   6  21  68  99   6  21  35  89]


In [103]:
# 39.Generate a 10×10 random decimal matrix.
arr = np.random.rand(10,10)
print(arr)

[[0.13564564 0.73763103 0.78495225 0.81998901 0.45694533 0.7400252
  0.49959189 0.0479399  0.55728866 0.6272305 ]
 [0.71337288 0.39105751 0.40906    0.60257533 0.34953296 0.94082109
  0.42078207 0.14618561 0.39978732 0.31125231]
 [0.30767449 0.08971703 0.11410557 0.4008278  0.74888218 0.79517455
  0.69429502 0.92330352 0.02820558 0.6890983 ]
 [0.2481966  0.35168202 0.90988655 0.27582215 0.84549142 0.10743852
  0.93185235 0.97000369 0.19255748 0.71072713]
 [0.12018518 0.11967277 0.65433394 0.48861636 0.67437009 0.35988924
  0.11726346 0.05527157 0.43613223 0.13780728]
 [0.18174329 0.74245642 0.82403961 0.67074143 0.52097755 0.86054396
  0.73984306 0.02824922 0.32951072 0.66141592]
 [0.71184774 0.72445676 0.92009877 0.60539252 0.95180906 0.61391685
  0.51915398 0.58923421 0.72023986 0.7650384 ]
 [0.37559906 0.79814212 0.84472733 0.50532589 0.40920866 0.41418629
  0.17792216 0.73811238 0.01257134 0.94865195]
 [0.65177526 0.51631083 0.09095375 0.25349778 0.33268885 0.32466025
  0.71927057 

In [104]:
# 40.Create a 5×5 matrix filled with random integers between 100 and 999.
arr = np.random.randint(100,999,(5,5))
print(arr)
                        

[[340 272 230 930 508]
 [501 615 884 940 624]
 [834 556 162 399 604]
 [222 851 165 909 259]
 [642 820 245 807 186]]


In [107]:
# 41.Create an array containing the squares of numbers from 1 to 20.
arr =np.arange(1,21) ** 2
print(arr)
#m2
import numpy as np

arr = np.arange(1, 21)
squares = arr * arr

print(squares)

[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361 400]


In [108]:
# 42.Create an array containing the cubes of numbers from 1 to 10.
arr = np.arange(1,101) ** 3
print(arr)

[      1       8      27      64     125     216     343     512     729
    1000    1331    1728    2197    2744    3375    4096    4913    5832
    6859    8000    9261   10648   12167   13824   15625   17576   19683
   21952   24389   27000   29791   32768   35937   39304   42875   46656
   50653   54872   59319   64000   68921   74088   79507   85184   91125
   97336  103823  110592  117649  125000  132651  140608  148877  157464
  166375  175616  185193  195112  205379  216000  226981  238328  250047
  262144  274625  287496  300763  314432  328509  343000  357911  373248
  389017  405224  421875  438976  456533  474552  493039  512000  531441
  551368  571787  592704  614125  636056  658503  681472  704969  729000
  753571  778688  804357  830584  857375  884736  912673  941192  970299
 1000000]


In [110]:
# 43.Create a 4×4 matrix where all elements are random integers between 1 and 9.
arr = np.random.randint(1,9,(4,4))
print(arr)

[[5 7 4 2]
 [4 2 6 3]
 [3 5 2 8]
 [8 7 1 2]]


In [113]:
# 44.Generate 50 evenly spaced numbers between 0 and 100.
arr = np.linspace(0,100,50)
print(arr)

[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]


In [116]:
# 45.Create a sequence from 0 to 100 with a step of 0.5.
arr = np.arange(0,100.5,0.5)
print(arr)

[  0.    0.5   1.    1.5   2.    2.5   3.    3.5   4.    4.5   5.    5.5
   6.    6.5   7.    7.5   8.    8.5   9.    9.5  10.   10.5  11.   11.5
  12.   12.5  13.   13.5  14.   14.5  15.   15.5  16.   16.5  17.   17.5
  18.   18.5  19.   19.5  20.   20.5  21.   21.5  22.   22.5  23.   23.5
  24.   24.5  25.   25.5  26.   26.5  27.   27.5  28.   28.5  29.   29.5
  30.   30.5  31.   31.5  32.   32.5  33.   33.5  34.   34.5  35.   35.5
  36.   36.5  37.   37.5  38.   38.5  39.   39.5  40.   40.5  41.   41.5
  42.   42.5  43.   43.5  44.   44.5  45.   45.5  46.   46.5  47.   47.5
  48.   48.5  49.   49.5  50.   50.5  51.   51.5  52.   52.5  53.   53.5
  54.   54.5  55.   55.5  56.   56.5  57.   57.5  58.   58.5  59.   59.5
  60.   60.5  61.   61.5  62.   62.5  63.   63.5  64.   64.5  65.   65.5
  66.   66.5  67.   67.5  68.   68.5  69.   69.5  70.   70.5  71.   71.5
  72.   72.5  73.   73.5  74.   74.5  75.   75.5  76.   76.5  77.   77.5
  78.   78.5  79.   79.5  80.   80.5  81.   81.5  8

In [120]:
# 46.Generate a 3×3×3 array of random integers.
arr = np.random.randint(1,100,((3,3,3)))
print(arr)

[[[45 91 88]
  [88  6 28]
  [48 90 84]]

 [[22 75 47]
  [96 55  8]
  [34 42 31]]

 [[42 44 62]
  [54 79 13]
  [59 15 99]]]


In [124]:
# 47.Generate a 2×4×3 array of ones.
arr = np.ones(((2,4,3)))
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [125]:
# 48.Generate a 3×3×3 array of zeros.
arr = np.zeros(((3,3,3)))
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [130]:
# 49.Create a 7×7 identity matrix and verify its diagonal values.
arr = np.eye(7,7)
print(arr)

print("The Digonal values:",np.diag(arr))

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
The Digonal values: [1. 1. 1. 1. 1. 1. 1.]


In [152]:
# 50.Challenge: Create a matrix that contains:
#    First row → zeros
#    Second row → ones
#    Third row → random integers
#    Fourth row → evenly spaced values using linspace()

arr = np.zeros((4,4))

arr[0] = np.zeros(4)
arr[1] = np.ones(4)
arr[2] = np.random.randint(1,10,(4,))
arr[3] = np.linspace(1,10,4)
print(arr)

[[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 5.  2.  3.  6.]
 [ 1.  4.  7. 10.]]
